### ISSUE TITLE
After /reload plugin broke 

### ISSUE THREAD

**Issue by ZipFox189** [TWME-TW/DebugStickPro#13]
After /reload plugin broking:

[00:19:17 WARN]: [DebugStickPro] Task #7 for DebugStickPro v0.4.6 generated an exception
java.lang.NullPointerException: Cannot invoke "dev.twme.debugstickpro.playerdata.PlayerData.getDebugStickMode()" because "playerData" is null
        at DebugStickPro-0.4.6.jar/dev.twme.debugstickpro.display.ActionBarDisplayTask.run(ActionBarDisplayTask.java:35) ~[DebugStickPro-0.4.6.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-90-b149584]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-90-b149584]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-90-b149584]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-90-b149584]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-90-b149584]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-90-b149584]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-90-b149584]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by TWME-TW** [comment]
After testing, I cannot reproduce this error. Can you provide the complete log?

**Comment by ZipFox189** [comment]
[2024-06-09-4.log](https://github.com/user-attachments/files/15754242/2024-06-09-4.log)
Here is log

**Comment by TWME-TW** [comment]
> [2024-06-09-4.log](https://github.com/user-attachments/files/15754242/2024-06-09-4.log) Here is log

Please try to use this version: https://github.com/TWME-TW/DebugStickPro/releases/tag/0.4.7-SNAPSHOT

**Comment by ZipFox189** [comment]
Yeah. Problem gone. Thx)
